# REDIRECCIÓN HTTP → HTTPS
server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

# SERVICIO ODOO HTTPS (DEV)
server {
    listen 443 ssl;
    server_name localhost;
    client_max_body_size 0;

    # Certificados mkcert (DEV)
    ssl_certificate     /etc/nginx/certs/tls/localhost-cert.pem;
    ssl_certificate_key /etc/nginx/certs/tls/localhost-key.pem;

    location / {
        proxy_pass http://odoo_sembrem:8069;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        # Para WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_read_timeout 720s;
        proxy_send_timeout 720s;
    }
}
